env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - plugin:regexp/recommended
  - plugin:unicorn/recommended
  - plugin:promise/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.eslint.json
plugins:
  - '@typescript-eslint'
  - regexp
  - unicorn
  - promise
rules:
  unicorn/prefer-module: off
